### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by slawiko** [DaryaSht/Practice#1]
@DaryaSht 

- Фильтры
Не Sort, а Filter - это разные вещи.
Получается можно искать только одно значение? Выбирается по чему фильтровать и в поле поиска вписывается значение? В таком случае это не очень удобно.

- UserPage
Страница вне ТЗ, поэтому за нее снижать ничего не будем, но есть пара вопросов и советов:
Во-первых не понятно назначение страницы.
Во-вторых: зачем на этой странице фильтровать по автору? Я так понял на этой странице и так посты одного автора?
В-третьих: не торопитесь замахиваться на что-то вне ТЗ. Это круто, если сделаете. Но если сделаете это в ущерб основному заданию - будет не очень хорошо.

**Comment by DaryaSht** [comment]
Спасибо, я доделаю

**Comment by slawiko** [comment]
@DaryaSht 

в следующий раз, когда поправите наши замечания, отпишите в issue, а то чуть не случилось недопонимание :)

**Comment by DaryaSht** [comment]
Ок)
