### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by slawiko** [DaryaSht/Practice#2]
@DaryaSht 

Не забывайте ставить тэг. Иначе мы не понимаем можно ли проверять вашу работу. Уже можно?

**Comment by DaryaSht** [comment]
Да

**Comment by slawiko** [comment]
Все файлы в одной папке это плохо. Сортируйте их как-нибудь. Картинки, стили... 

CSS:
- немножко страдает форматирование. Старайтесь писать консистентно.

HTML:
- зачем вам элемент `<header>` внутри которого один `<div.header>`? Что-то из этого лишнее.
- тут тоже с форматированием есть огрехи.

Responsive не получился. Хэдер как-то не посередине. При сужении окна появляется скролл, то есть посты не удачно подстраиваются под разрешение.

**Comment by slawiko** [comment]
@DaryaSht отреагируйте как-нибудь, не знаем дошла ли до вас информация

**Comment by DaryaSht** [comment]
Да, поняла
